In [6]:
import os
import requests
import json
from dotenv import load_dotenv
import pandas as pd
import geopandas as gpd
from cartoframes.viz import Map, Layer, popup_element
import os
from dotenv import load_dotenv
load_dotenv() 
token = os.getenv("token")

In [7]:
# For each city select in a 1km radius the venues existing through foursquare and compare the number for each city
# BARS / SCHOOLS / AIRPORTS / STARBUCKS / DESIGN COMPANIES / VEGAN RESTAURANTS

# FUNCTIONS

In [8]:
# Funtion to get the number of venues

def requests_for_foursquare (query, lat, lon, radius, limit=40):

    url = f"https://api.foursquare.com/v3/places/search?query={query}&ll={lat}%2C{lon}&radius={radius}&limit={limit}"

    headers = {
        "accept": "application/json",
        "Authorization": token
    }
    
    try:
        return requests.get(url, headers=headers).json()
    except:
        print("no :(")

In [9]:
# Function to extract the desired information of each selected venue

def extracting_from_one_element (general):

    name = general["name"]
    address = general["location"]["address"]
    distance = general["distance"]
    zip_code = general["location"]["postcode"]
    lat = general["geocodes"]["main"]["latitude"]
    lon = general["geocodes"]["main"]["longitude"]

    
    small_dict = {
    "name": name,
    "address": address,
    "zip_code": zip_code,
    "distance": distance,
    "lat": lat,
    "lon": lon
    }
    return small_dict

In [10]:
# Function to transform the extracted information into a DF

def transform_request_into_df (res):
    list_of_dictionaries = [extracting_from_one_element (element) for element in res["results"]]
    return pd.DataFrame(list_of_dictionaries)

# COORDINATES

In [11]:
# LATITUDE MONTREAL / TORONTO / OTTAWA

lat_mo =  45.508210
lon_mo = -73.568340

tor_lat = 43.654770 
tor_lon = -79.392346

ott_lat = 45.409977
ott_lon = -75.701231

# BARS

In [12]:
# Request and DF for BARS / NIGHT CLUBS in Montreal

bars_mo = requests_for_foursquare ("beer", lat_mo, lon_mo, radius=1000, limit = 28)
df_bars_mo = transform_request_into_df (bars_mo)
df_bars_mo

,name,address,zip_code,distance,lat,lon
0,Benelux,245 Sherbrooke Rue O,H2X 1X7,258,45.509571,-73.571023
1,Les 3 Brasseurs,732 Sainte-Catherine Rue O,H3B 1B9,691,45.502195,-73.570593
2,Le Saint Bock,1749 Saint-Denis Rue,H2X 3K4,887,45.515893,-73.564685
3,La Cage,150 St Catherine Rue W,H2X 3Y2,240,45.507661,-73.564375
4,Bar Pamplemousse,1579 Saint-Laurent Blvd,H2X 2S9,350,45.510929,-73.565738
5,Sainte-Elisabeth,1412 Sainte-Elisabeth Rue,H2X 3C6,641,45.512194,-73.562146
6,Bar le Mal Nécessaire,1106B Saint Laurent Blvd,H2Z 1J5,555,45.508519,-73.561303
7,Foufounes Electriques,87 Sainte-Catherine Rue E,H2X 1K5,511,45.510982,-73.563125
8,McKibbin's Irish Pub,3515 Saint-Laurent Blvd,H2X 2T6,616,45.513430,-73.571243
9,Saint-Houblon,1567 Saint-Denis Rue,H2X 3K3,853,45.514696,-73.562032
10,Nacarat,900 René-Lévesque O,H3B 4A5,826,45.500712,-73.568076
11,Randolph Pub Ludique,2041 Saint-Denis Rue,H2X 3K8,923,45.516495,-73.565819
12,Furco,425 Mayor Rue,H3A 1N9,276,45.505916,-73.569211
13,Le 4e Mur,2021 Saint-Denis Rue,H2X 3K8,915,45.516216,-73.565568
14,Ye Olde Orchard Pub & Grill,20 Prince-Arthur Rue O,H2X 1S3,689,45.513458,-73.572649
15,SuWu,3581 Saint-Laurent Blvd,H2X 2T6,703,45.513976,-73.572326
16,Les 3 Brasseurs,1658 Saint-Denis Rue,H2X 3K6,840,45.514950,-73.563541
17,Arcade MTL,2031 Saint-Denis Rue,H2X 3K8,930,45.516495,-73.565819
18,Pub l'Ile Noire,1649 Saint-Denis Rue,H2X 3K4,865,45.515237,-73.563405
19,Club Pelicano,1076 Rue de Bleury,H2Z 1N2,566,45.504442,-73.563449
20,Poincaré Chinatown,1071 Saint Laurent Blvd,H2Z 1J6,617,45.508538,-73.560335
21,Brasserie Artisanale l'Amère a Boire Inc,2049 Saint-Denis Rue,H2X 3K8,921,45.516435,-73.565962
22,Patrick'S Pub Irlandais,1707 Saint-Denis Rue,H2X 3K4,876,45.515508,-73.564043
23,Suite 701,701 cote de la Place-d'Armes,H2Y 2X6,901,45.505358,-73.557473
24,Sarah B. Bar Absinthe,360 Saint-Antoine Rue O,H2Y 3X4,825,45.502899,-73.561076
25,SHAKER Cuisine & Mixologie,3518 Saint-Laurent Blvd,H2X 2V1,582,45.512978,-73.571132
26,Le Vieux Dublin Pub & Restaurant,636 Cathcart Rue,H3B 1L9,578,45.503031,-73.568586
27,Nyks Bistro Pub,1250 Rue de Bleury,H3B 2W4,259,45.506024,-73.566648

In [13]:
# Saving df into csv
df_bars_mo.to_csv("../DATA/bars_mo.csv")

In [14]:
# Request and DF for BARS / NIGHT CLUBS in Toronto

bars_to = requests_for_foursquare ("beer", tor_lat, tor_lon, radius=1000, limit=27)
df_bars_to = transform_request_into_df (bars_to)
df_bars_to

,name,address,zip_code,distance,lat,lon
0,Sin and Redemption,136 McCaul St,M5T 1W2,50,43.654588,-79.391728
1,Town Crier Pub,115 John St,M9N 1J9,759,43.648185,-79.390240
2,Bar Hop Brewco,137 Peter St,M5V 2H3,639,43.649093,-79.393190
3,The Queen and Beaver Public House,35 Elm St,M5G 1H1,770,43.657380,-79.383430
4,The 3 Brewers,275 Yonge St,M5B 1N8,962,43.655472,-79.380321
5,Prenup Pub,191 College St,M5T 1P9,498,43.658801,-79.394784
6,Cold Tea,60 Kensington Ave,M5T 2K1,704,43.654218,-79.400693
7,Soho House,192 Adelaide St W,M5H 0A4,817,43.648800,-79.386412
8,Queen St Warehouse,232 Queen St W,M5V 1Z6,542,43.650216,-79.390097
9,Grey Gardens,199 Augusta Ave,M5T 2L4,744,43.653818,-79.401564
10,Trinity Common,303 Augusta Ave,M5T 2M2,861,43.656656,-79.402671
11,The Embassy Bar,223 Augusta Ave,M5T 2L4,765,43.654307,-79.401782
12,Ronnie's Local 069,69 Nassau St,M5T 1M6,831,43.655023,-79.402738
13,Cameron House,408 Queen St W,M5V 2A7,802,43.648601,-79.397646
14,Bang Sue Bar,11 Charlotte St,M5V 0M6,956,43.646428,-79.393560
15,The Rivoli,334 Queen St W,M5V 2A2,659,43.649247,-79.394944
16,Village Idiot Pub,126 Mc Caul St,M5T 1W2,71,43.654366,-79.391693
17,Grace O'Malley's,14 Duncan St,M5H 3G8,847,43.647685,-79.388618
18,Earl's Kitchen & Bar,150 King St W,M5H 1J9,1028,43.648085,-79.384662
19,Handlebar,159 Augusta Ave,M5T 2L4,749,43.652891,-79.401182
20,Kensington Brewing Co,299 Augusta Ave,M5T 2M2,854,43.656441,-79.402543
21,The Porch,250 Adelaide St W,M5H 1X6,772,43.648338,-79.388909
22,Elephant & Castle,212 King St W,M5H 1K5,931,43.647513,-79.386347
23,Watson's,388A Richmond St W,M5V 3P1,786,43.648169,-79.395100
24,Art Gallery of Ontario,317 Dundas St W,M5T 1G4,97,43.653538,-79.392624
25,Friar & Firkin,160 John St,M5V 2E5,598,43.649574,-79.391210
26,Wide Open,139A Spadina Ave,M5V 2K8,839,43.647685,-79.395583

In [15]:
# Saving df into csv

df_bars_to.to_csv("../DATA/bars_to.csv")

In [16]:
# Request and DF for BARS / NIGHT CLUBS in Ottawa

bars_ot = requests_for_foursquare ("beer", ott_lat, ott_lon, radius=1000, limit=50)
df_bars_ot = transform_request_into_df (bars_ot)
df_bars_ot

,name,address,zip_code,distance,lat,lon
0,Flora Hall Brewing,37 Flora St,K2P 1A7,632,45.410763,-75.693422
1,Pour Boy Pub,495 Somerset St W,K1R 5J7,422,45.413846,-75.700400
2,Atomic Rooster,303 Bank St,K2P 1X7,688,45.414938,-75.695740
3,Prohibition Public House,337 Somerset St W,K2P 0J8,798,45.415919,-75.695382
4,Beer Store,515 Somerset St W,K1R 5J9,401,45.413589,-75.701154
5,Union Local 613,315 Somerset St W,K2P 0J8,847,45.416102,-75.695057
6,Clock Tower Brew Pub,575 Bank St,K1S 5L7,803,45.408460,-75.691204
7,The Greek Souvlaki Shack,258 Bank St,K2P 1X4,756,45.416074,-75.697235
8,Spark Beer,702 Somerset St W,K1R 6P6,463,45.410685,-75.707074
9,Blue Nile Ethiopian Restaurant,577 Gladstone Ave,K1R 5P2,88,45.409511,-75.700732
10,The WORKS Craft Burgers & Beer,580 Bank St,K1S 3T3,805,45.407882,-75.691449
11,Gongfu Bao,365 Bank St,K2P 1Y2,659,45.414061,-75.694895
12,The Gilmour,313 Bank St,K2P 1X9,679,45.414664,-75.695476
13,Jabberwocky Bar,315 Somerset St W,K2P 0J8,845,45.416102,-75.695057
14,Jax,479 Bronson Ave,K1R 6J7,330,45.407536,-75.703239
15,Royal Oak Restaurant,318 Bank St,K2P 1Y1,664,45.414481,-75.695800
16,Colonnade Pizza & Restaurant,280 Metcalfe St,K2P 1R7,1009,45.415725,-75.691588
17,Yangtze,700 Somerset St W,K1R 6P6,458,45.410869,-75.706749
18,The Royal Oak Pubs,180 Kent St,K1P 0B6,936,45.417949,-75.701647
19,Pho Thu Do,781 Somerset St W,K1R 6R3,689,45.409935,-75.710259
20,Divino Wine Studio,225 Preston St,K1R 7R1,1002,45.405536,-75.712232
21,Erling's Variety,225 Strathcona Ave,K1S 1X7,879,45.407572,-75.690649
22,Roast N Curries,197 Bank St,K2P 1W7,872,45.417690,-75.698090
23,Cafe Nakheel,575 Gladstone Ave,K1R 5P2,88,45.409244,-75.700275
24,GO Wine Trail,25 Murray St,K1N 9M5,270,45.412132,-75.699149
25,Rough Rider Tap House,93 Florence St,K1R 5N1,333,45.411355,-75.697198
26,Royal Canadian Legion,330 Kent St,K2P 2A6,478,45.413874,-75.698222
27,Gladstone Lounge,750 Gladstone Ave,K1R 6X5,478,45.406828,-75.705361
28,Café sketch,240 Bronson,K1R 1B5,507,45.412877,-75.706280
29,Whalebones,Rue Bank St,K2P 1Y8,630,45.412328,-75.694127
30,recLINK,755 Somerset St W,K1R 6R1,667,45.410551,-75.709049
31,Royal Oak,188 Bank St,K2P 1W8,898,45.417726,-75.698626
32,Arlo,340 Somerset St W,K2P 0J9,769,45.415465,-75.695346
33,T's Pub,323 Somerset St W,K2P 0J8,794,45.416102,-75.695057
34,Chateau des Charmes Wines,407 Laurier Ave W,K1R 7Y7,801,45.417411,-75.702331
35,Mekong Restaurant,637 Somerset St W,K1R 5K3,350,45.412023,-75.704856
36,Occo Kitchen,160 Bay St,K1R 7X8,917,45.417534,-75.706458
37,Knyota Non-Alcoholic Drinks,104 Bank St,K1P 5N4,241,45.411123,-75.698778
38,Ward 14 Consignment Bar,139 Preston St,K1R 7P4,1087,45.407649,-75.713466
39,Baton Rouge,360 Albert Rue,K1R 7X7,974,45.418144,-75.703940
40,Corner Peach,802 Somerset St W,K1R 6R5,741,45.409185,-75.710538
41,J:unique Kitchen,381 Cooper St,K2P 0G8,800,45.416389,-75.696437

In [382]:
# Saving df into csv

df_bars_ot.to_csv("../DATA/bars_ot.csv")

# SCHOOLS

In [447]:
# Request and DF for SCHOOLS in Montreal

schools_mo = requests_for_foursquare ("schools", lat_mo, lon_mo, radius=2000, limit=18)
df_sch_mo = transform_request_into_df (schools_mo)
df_sch_mo

,name,address,zip_code,distance,lat,lon
0,Ithq,3535 Saint-Denis Rue,H2X 3P1,1080,45.517916,-73.568577
1,BLI Bouchereau Lingua International,70 Notre Dame Rue W,H2Y 1S6,987,45.505099,-73.556254
2,McGill Schulich School of Music,555 Sherbrooke St W,H3A 1E3,442,45.505777,-73.573226
3,Technologia,440 Rene-Levesque Blvd O,H2Z 1V7,475,45.504353,-73.565045
4,Genome Building,740 Docteur Penfield,H3A 0G1,880,45.506960,-73.579318
5,Rfavq,405 de Maisonneuve Est,H2L 4J5,909,45.514987,-73.561702
6,McGill Duff Medical Building,3775 University St,H3A 2B4,933,45.508816,-73.580201
7,Hupo Mandarin,1625 Lincoln Ave,H3H 2T5,1674,45.495907,-73.580899
8,École des métiers de la restauration et du tou...,1822 Blvd de Maisonneuve Ouest,H3H 1J8,1861,45.493869,-73.580543
9,Ilsc,550 Sherbrooke Rue O,H3A 1B9,409,45.505683,-73.572255
10,Arabic Mtl,1245 Saint-Dominique Rue,H2X 2W4,513,45.510089,-73.562321
11,Elam,1080 Cote du Beaver Hall,H2Z 1S8,667,45.502648,-73.565087
12,Propulsion RH,1117 Sainte-Catherine Rue O,H3B 1H9,1012,45.499704,-73.572983
13,École de Conduite Acom,859 Blvd de Maisonneuve E,H2L 1Y8,1157,45.516839,-73.560017
14,Koncept Formation,417 Saint-Pierre Rue,H2Y 2M4,1166,45.501625,-73.556677
15,Concorida University School,2145 MacKay Rue,H3G 2J2,1499,45.497405,-73.579882
16,EC Montreal,1610 St Catherine St W,H3H 2S2,1742,45.494198,-73.578375
17,Académie de Danse Titosalsabor,4416 St Laurent,H2W 1Z5,1812,45.519393,-73.585289

In [384]:
df_sch_mo.to_csv("../DATA/schools_mo.csv")

In [451]:
# Request and DF for SCHOOLS in Toronto

schools_to = requests_for_foursquare ("schools", tor_lat, tor_lon, radius=2000, limit=20)
df_sch_to = transform_request_into_df (schools_to)
df_sch_to

,name,address,zip_code,distance,lat,lon
0,Ilsc,443 University Ave,M5G 2H6,366,43.654596,-79.387756
1,Royal Conservatory of Music,273 Bloor St W,M5S 1W2,1529,43.668027,-79.396069
2,Beverly Junior Public School,64 Baldwin St,M5T 1L4,256,43.655724,-79.395416
3,Medical Sciences Building,1 King's College Cir,M5S 1A8,743,43.660698,-79.393403
4,Studio 123,401 Richmond St W,M5V 3A8,792,43.647915,-79.394732
5,Tammie Norn,1 Dundas St W,M6P 2A1,862,43.655829,-79.381593
6,Saint Joseph College,74 Wellesley St W,M5S 1C4,1094,43.664175,-79.388814
7,St. Michael's Choir School,66 Bond St,M5B 1X2,1159,43.655078,-79.378014
8,Central Technical School,725 Bathurst St,M5S 2R5,1615,43.663965,-79.408701
9,Easy Driving School,996 Dundas St W,M6J 1W6,1920,43.650497,-79.415573
10,Huron Street Jr PS,541 Huron St,M5R 2R6,1936,43.671018,-79.402813
11,International Finance Institute,151 Yonge St,M5C 2W7,1344,43.648986,-79.377653
12,Toronto Preschool Speech and Language Svc,1075 Bay St,M5S 2B1,1398,43.667056,-79.388571
13,Music& Art School,134 Carlton St,M5A 2K1,1638,43.663063,-79.375497
14,Write City Inc,720 Bathurst St,M5S 2R4,1758,43.663190,-79.410869
15,"Anthony Santen, MCH CCLC NLP CI",101B Roncesvalles Ave,M6R 2K9,1797,43.670520,-79.387253
16,Isabel Bader Theatre,93 Charles St W,M5S 1K5,1395,43.667172,-79.392378
17,University of Toronto Athletic Centre,55 Harbord St,M5S 2W6,1087,43.663040,-79.401352
18,Innis Town Hall,2 Sussex Dr,M8V 1W4,1317,43.665414,-79.399580
19,Convocation Hall,31 King's College Cir,M5S 3K1,712,43.660890,-79.395398

In [388]:
df_sch_to.to_csv("../DATA/schools_to.csv")

In [453]:
# Request and DF for SCHOOLS in Ottawa

schools_ot = requests_for_foursquare ("schools", ott_lat, ott_lon, radius=2000, limit=10)
df_sch_ot = transform_request_into_df (schools_ot)
df_sch_ot

,name,address,zip_code,distance,lat,lon
0,Fast French Seminars,211 Bronson Ave,K1R 6H5,591,45.413465,-75.707247
1,Centennial Public School,376 Gloucester St,K1R 5E8,611,45.414928,-75.704749
2,St Anthony School,391 Booth St,K1R 7K5,673,45.406375,-75.708231
3,Adult High School,300 Rochester St,K1R 7N4,923,45.404375,-75.709912
4,Heart to Heart First Aid CPR Ottawa,Hill 402 Queen St,K1R 5A7,971,45.417750,-75.706766
5,ExitCertified Corp,220 Laurier Ave W,K1P 5Z9,1117,45.419587,-75.696110
6,Corpus Christi School,157 4th Ave,K1S 2L5,1231,45.401415,-75.691032
7,Centre de Formation Professionnelle & Linguist...,130 Slater St,K1P 6E2,1250,45.420655,-75.696437
8,First Avenue School,73 1st Ave,K1S 2G1,1311,45.406520,-75.685529
9,Devonshire School,100 Breezehill Ave N,K1Y 2H5,1441,45.405732,-75.718834

In [391]:
df_sch_ot.to_csv("../DATA/schools_ot.csv")

# AIRPORTS

In [195]:
# Request and DF for AIRPORTS in Montreal

plane_mo = requests_for_foursquare (("airport"), lat_mo, lon_mo, radius= 25000, limit=1)
df_plane_mo = transform_request_into_df (plane_mo)
df_plane_mo

,name,address,zip_code,distance,lat,lon
0,Montréal-Pierre Elliott Trudeau International ...,975 Roméo-Vachon Blvd N,H4Y 1H1,15323,45.45782,-73.75133

In [196]:
df_plane_mo.to_csv("../DATA/air_mo.csv")

In [331]:
# Request and DF for AIRPORTS in Toronto

plane_to = requests_for_foursquare ("Aéroport", tor_lat, tor_lon, radius=20000, limit=2)
df_plane_to = transform_request_into_df (plane_to)
df_plane_to

,name,address,zip_code,distance,lat,lon
0,Toronto Pearson International Airport (YYZ),6301 Silver Dart Dr,L5P 1B2,18102,43.67772,-79.62482
1,Billy Bishop Toronto City Airport (YTZ),1 Island Airport,M5V 1A1,2583,43.63180,-79.39729

In [332]:
df_plane_to.to_csv("../DATA/air_to.csv")

In [205]:
# Request and DF for AIRPORTS in Ottawa

plane_ot = requests_for_foursquare ("Airport", ott_lat, ott_lon, radius=20000, limit=1)
df_plane_ot= transform_request_into_df (plane_ot)
df_plane_ot

,name,address,zip_code,distance,lat,lon
0,Ottawa Macdonald-Cartier International Airport...,1000 Airport Pky Pvt,K1V 9B4,10077,45.317844,-75.665885

In [206]:
df_plane_ot.to_csv("../DATA/air_ot.csv")

# STARBUCKS

In [209]:
# Request and DF for STARBUCKS in Montreal

starbucks_mo = requests_for_foursquare ("Starbucks", lat_mo, lon_mo, radius=1000, limit=10)
df_starbucks_mo= transform_request_into_df (starbucks_mo)
df_starbucks_mo

,name,address,zip_code,distance,lat,lon
0,Starbucks,475 Sherbrooke Rue O,H3A 2L9,357,45.506759,-73.572434
1,Starbucks,1446 Saint Laurent Blvd,H2X 1J5,349,45.510371,-73.565236
2,Starbucks,1500 McGill College Ave,H3A 3J5,723,45.502273,-73.572339
3,Starbucks,1001 Robert Bourassa Blvd,H3B 4L4,854,45.501072,-73.564359
4,Starbucks,1 Ville Marie Pl,H3B 3Y1,653,45.501736,-73.568012
5,Starbucks,3601 St-Laurent Blvd,H2X 2V5,731,45.514084,-73.572620
6,Starbucks,977 Sainte-Catherine Rue O,H3B 4W3,842,45.501086,-73.572059
7,Café Starbucks Eaton Center,705 Sainte-Catherine Rue O,H3B 4G5,614,45.502880,-73.570422

In [210]:
df_starbucks_mo.to_csv("../DATA/starbucks_mo.csv")

In [392]:
# Request and DF for STARBUCKS in Toronto

starbucks_to = requests_for_foursquare ("Starbucks", tor_lat, tor_lon, radius=1000, limit=10)
df_starbucks_to = transform_request_into_df (starbucks_to)
df_starbucks_to

        name               address zip_code  distance        lat        lon
0  Starbucks    585 University Ave  M5G 2N2       466  43.658198 -79.389171
1  Starbucks     338 Adelaide St W  M5V 1R4       798  43.647619 -79.392628
2  Starbucks    439 University Ave  M5G 1Y8       415  43.654440 -79.387590
3  Starbucks        203 College St  M5T 0C8       487  43.658532 -79.395396
4  Starbucks    555 University Ave  M5G 1X8       542  43.657705 -79.387456
5  Starbucks      111 Elizabeth St  M5G 1P7       597  43.655150 -79.384758
6  Starbucks        250 Queen St W  M5V 1Z7       536  43.650097 -79.390966
7  Starbucks    661 University Ave  M5G 1M1       554  43.659555 -79.389808
8  Starbucks          444 Yonge St  M5B 2H4       966  43.660750 -79.383405
9  Starbucks  1 King's College Cir  M5S 1A8       688  43.660854 -79.393569

In [334]:
df_starbucks_to.to_csv("../DATA/starbucks_to.csv")

In [393]:
# Request and DF for STARBUCKS in Ottawa

starbucks_ot = requests_for_foursquare ("Starbucks", ott_lat, ott_lon, radius=1000, limit=10)
df_starbucks_ot = transform_request_into_df (starbucks_ot)
df_starbucks_ot

        name        address zip_code  distance        lat        lon
0  Starbucks    455 Bank St  K2P 1Y9       648  45.411853 -75.693169
1  Starbucks  340 Albert St  K1R 7Y6       963  45.418713 -75.702483
2  Starbucks    296 Bank St  K2P 1X8       702  45.415048 -75.695845

In [394]:
df_starbucks_ot.to_csv("../DATA/starbucks_ot.csv")

# DESIGN COMPANIES

In [455]:
# Request and DF for DESIGN COMPANIES in Montreal

design_mo = requests_for_foursquare ("design", lat_mo, lon_mo, radius=1000, limit=4)
df_design_mo = transform_request_into_df (design_mo)
df_design_mo

,name,address,zip_code,distance,lat,lon
0,Theocharis Sergkei design,1445 Clark Rue,H2X 0C4,326,45.510259,-73.565136
1,International Photo Imaging,159 Sainte Antoine Rue O,H2Z 2A7,534,45.504984,-73.559108
2,DevFortress,3 Ville-Marie Pl,H3B 2E3,733,45.501611,-73.568589
3,Reelstreet,20 Guilbault Rue E,H2X 1A1,857,45.514795,-73.573951

In [280]:
df_design_mo.to_csv("../DATA/design_mo.csv")

In [460]:
# Request and DF for DESIGN COMPANIES in Toronto

design_to = requests_for_foursquare ("design", tor_lat, tor_lon, radius=1000, limit=19)
df_design_to = transform_request_into_df (design_to)
df_design_to

,name,address,zip_code,distance,lat,lon
0,Normative Design Inc,91 Oxford St,M5T 1P2,912,43.655740,-79.403694
1,Umbra Concept Store,165 John St,M5T 1X3,493,43.650482,-79.391074
2,TLAC Toronto Printing & Publishing,525 University Ave,M5G 2L3,373,43.656254,-79.388113
3,Artez Interactive Inc,215 Spadina Ave,M5T 2C7,554,43.650745,-79.396726
4,Hot Pop Factory,215 Spadina Ave,M5T 2C7,595,43.650686,-79.396763
5,Konrad Group,197 Spadina Ave,M5T 2C8,630,43.649714,-79.396234
6,Cundari Group,26 Duncan St,M5V 2B9,713,43.648612,-79.389000
7,A Nerd's World,164A Spadina Ave,M5T 2C2,735,43.649054,-79.396830
8,Radhikajain.Com,111 Peter St,M5V 2H1,741,43.647920,-79.392349
9,Laboratory Laboratory Laboratory,148 Augusta Ave,M5T 2L5,754,43.652513,-79.400981
10,Stinson Design,401 Richmond St W,M5V 3A8,759,43.647804,-79.394714
11,Loopmedia Inc,401 Richmond St W,M5V 3A8,805,43.647888,-79.395102
12,Orbital Arts,275 Augusta Ave,M5T 2M1,818,43.655841,-79.402307
13,Worldsew Fabrics,511 Queen St W,M5V 2B4,908,43.647991,-79.399091
14,Rich DX Studio,350 King St W,M5V 3X5,917,43.646788,-79.390158
15,Meevo Digital,20 Camden St,M5V 1V1,918,43.647303,-79.396972
16,Guru Animation Studio Ltd,110 Spadina Ave,M5V 2K4,934,43.646874,-79.395922
17,Hello Pop Design,832 Bay St,M5S 1Z6,936,43.661978,-79.386593
18,Colette: Branding agency toronto,832 Bay St,M5S 1Z6,949,43.662096,-79.386519

In [405]:
df_design_to.to_csv("../DATA/design_to.csv")

In [461]:
# Request and DF for DESIGN COMPANIES in Toronto

design_ot = requests_for_foursquare ("Design", ott_lat, ott_lon, radius=1000, limit=5)
df_design_ot = transform_request_into_df (design_ot)
df_design_ot

,name,address,zip_code,distance,lat,lon
0,Globe Awards and Promotions,409 Bronson Ave,K1R 6J5,363,45.410610,-75.706099
1,Print in Ottawa,465B Gladstone Ave,K1R 5N7,380,45.410971,-75.696829
2,Randall's Decor,555 Bank St,K1S 5L7,815,45.408519,-75.691160

In [408]:
df_design_ot.to_csv("../DATA/design_ot.csv")

# VEGAN RESTAURANTS

In [467]:
# Request and DF for VEGAN RESTAURANTS in Montreal

vegan_mo = requests_for_foursquare ("vegan", lat_mo, lon_mo, radius=1000, limit=8)
df_vegan_mo = transform_request_into_df (vegan_mo)
df_vegan_mo

,name,address,zip_code,distance,lat,lon
0,Lola Rosa,276 Sainte-Catherine Rue O,H2X 2A1,200,45.506943,-73.566193
1,Lola Rosa Cafe,545 Milton Rue,H2X 1W5,582,45.507314,-73.575891
2,Foodchain,1212 McGill College Ave,H3B 4J8,735,45.501510,-73.570765
3,Copper Branch,1180 Blvd de Maisonneuve Ouest Stanley,H3A 3J2,523,45.504117,-73.571042
4,Resto Végo,1720 Saint-Denis Rue,H2X 3K6,874,45.515496,-73.564624
5,Freshii,3454 Park Ave,H2X 2H6,341,45.508855,-73.572743
6,Bouillon Bilk,1595 Saint-Laurent Blvd,H2X 2S9,363,45.511038,-73.565936
7,Dame Nature,895 Rue de la Gauchetiere Ouest,H3B 4G1,858,45.500009,-73.566359

In [317]:
df_vegan_mo.to_csv("../DATA/vegan_mo.csv")

In [479]:
# Request and DF for VEGAN RESTAURANTS in Toronto

vegan_to = requests_for_foursquare ("vegan restaurant", tor_lat, tor_lon, radius=1000, limit=40)
df_vegan_to = transform_request_into_df (vegan_to)
df_vegan_to

,name,address,zip_code,distance,lat,lon
0,Karine's,109 McCaul St,M5T 3K5,175,43.653858,-79.390957
1,Art Gallery of Ontario,317 Dundas St W,M5T 1G4,97,43.653538,-79.392624
2,Fresh on Spadina,147 Spadina Ave,M5V 2L7,802,43.648063,-79.395784
3,Moonbean Coffee Co,30 Saint Andrew St,M5T 1K6,633,43.654265,-79.400045
4,Essence of Life Organics,50 Kensington Ave,M5T 2K1,654,43.654055,-79.400620
5,Pai,18 Duncan St,M5H 3G8,818,43.647796,-79.388636
6,Rosalinda,133 Richmond St W,M5H 2L3,765,43.650207,-79.384813
7,Seven Lives,69 Kensington Ave,M5T 2K2,672,43.654297,-79.400378
8,Saigon Lotus,6 St Andrew St,M5T 1K6,555,43.654450,-79.399046
9,Kupfert & Kim,140 Spadina Ave,M5V 2L4,817,43.647697,-79.396193
10,Cafe Landwer,165 University Ave,M5H 3B8,872,43.648724,-79.385137
11,Dark Horse Espresso Bar,215 Spadina Ave,M5T 2C7,599,43.650738,-79.396818
12,Green Box,200 University Ave,M5H 3C6,567,43.649805,-79.386478
13,Daily Press Juicery,200 Queen St W,M5V 1Z2,564,43.650466,-79.388968
14,Ozzy's Burgers,66 Nassau St,M5T 1M5,826,43.655370,-79.402606
15,Bunners,244 Augusta Ave,M5T 2L7,819,43.655533,-79.402679
16,Big Fat Burrito,285 Augusta Ave,M5T 2M1,818,43.656004,-79.402380
17,Planta Queen,180 Queen St W,M5V 3X3,571,43.650697,-79.388116
18,Khao San Road,11 Charlotte St,M5V 0M6,948,43.646180,-79.393894
19,Elmwood Spa,18 Elm St,M5G 1G7,852,43.657832,-79.382614
20,Buddha's Vegetarian Foods,666 Dundas St W,M5T 1H9,937,43.651946,-79.403369
21,Chipotle Mexican Grill,323 Yonge St,M5B 1R7,948,43.656829,-79.380958
22,Asian Legend 味香村,418 Dundas St W,M5T 1G7,252,43.653713,-79.395282
23,King's Cafe,192 Augusta Ave,M5T 2L6,769,43.654065,-79.402024
24,Our Spot,180 Baldwin St,M5T 1L8,684,43.654884,-79.400799
25,Crepe Delicious,220 Yonge St,M5B 2H1,921,43.653696,-79.380039
26,Flock Rotisserie + Greens,661 University Ave,M5G 1M1,540,43.659347,-79.389588
27,Parka Food Co,424 Queen St W,M5V 2A7,838,43.648575,-79.398016
28,Cacao 70,485 Queen St W,M5V 2A9,849,43.648248,-79.397870
29,Greens Vegetarian Restaurant,638 Dundas St W,M5T 1H8,862,43.652118,-79.402555
30,Little India Restaurant,255 Queen St W,M5V 1Z4,563,43.650192,-79.388877
31,Kiin,326 Adelaide St W,M5V 1R3,817,43.647607,-79.392018
32,Aroma Espresso Bar,562 Bay St,M5G 0B3,705,43.655224,-79.383741
33,Smoke's Poutinerie Inc,218 Adelaide St W,M5H 1W7,809,43.648543,-79.387633
34,Village by the Grange,78 Saint Patrick St,M5T 3K8,176,43.652437,-79.389656
35,Mamma's Pizza,405 Richmond St W,M5V 1X3,803,43.647757,-79.395361
36,Freshii,140 Spadina Ave,M5V 2L4,818,43.647697,-79.396193
37,Basil Box Ryerson,351 Yonge St,M5B 1S1,923,43.657815,-79.381302
38,Veda Restaurant,10 King's College Rd,M5S 3G4,601,43.660029,-79.394887
39,Bo de Duyen 菩提緣素食樓,186 Spadina Ave,M5T 3B2,658,43.649713,-79.397029

In [413]:
df_vegan_to.to_csv("../DATA/vegan_to.csv")

In [481]:
# Request and DF for VEGAN RESTAURANTS in Ottawa

vegan_ot = requests_for_foursquare ("vegan restaurant", ott_lat, ott_lon, radius=1000, limit=20)
df_vegan_ot = transform_request_into_df (vegan_ot)
df_vegan_ot

,name,address,zip_code,distance,lat,lon
0,Moo Shu Ice Cream & Kitchen,477 Bank St,K2P 1Z2,670,45.410961,-75.692711
1,Burrito Gringo,566 Bronson Ave,K1R 6K3,488,45.405459,-75.702540
2,Bread & Sons Bakery,195 Bank St,K2P 1W7,885,45.417745,-75.698143
3,ThimbleCakes,369 Bank St,K2P 1Y2,650,45.413947,-75.694886
4,Jax,479 Bronson Ave,K1R 6J7,330,45.407536,-75.703239
5,Burgers n' Fries Forever,329 Bank St,K2P 1X9,655,45.414441,-75.695361
6,Herb & Spice Shop,375 Bank St,K2P 1Y2,649,45.413893,-75.694833
7,Atomic Rooster,303 Bank St,K2P 1X7,688,45.414938,-75.695740
8,Bridgehead,366 Bank St,K2P 1Y4,643,45.413874,-75.695316
9,Copper Branch,350 Albert St,K1R 1A4,937,45.418211,-75.703703

In [417]:
df_vegan_ot.to_csv("../DATA/vegan_ot.csv")